apiVersion: v1
kind: Secret
metadata:
  name: rails-secrets
type: Opaque
data:
  # Generate these with: echo -n "yourvalue" | base64
  master-key: eW91cl9tYXN0ZXJfa2V5X3ZhbHVl
  secret-key-base: eW91cl9zZWNyZXRfa2V5X2Jhc2VfdmFsdWU=
